# Generated by Django 5.2.7 on 2026-04-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="last_checkin",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="scan_requested",
            field=models.BooleanField(default=False),
        ),
    ]
